// ─────────────────────────────────────────────────────────────────────────────
// 🏆 wc-matches.js — Picks IA por PARTIDO del Mundial 2026
//
// Calendario oficial Mundial 2026 (sorteo FIFA 5-dic-2025, Washington DC).
// Picks regulares (no outright) para los primeros 7 días del Mundial.
// ─────────────────────────────────────────────────────────────────────────────

export const WC_MATCHES_PUBLISH_TS = Date.UTC(2026, 5, 9, 0, 0, 0); // publicación inmediata

function ART_ts(year, monthIdx, day, hourART, minART = 0) {
  return Date.UTC(year, monthIdx, day, hourART + 3, minART, 0);
}

// GRUPOS OFICIALES:
// A: México, Sudáfrica, Corea del Sur, República Checa
// B: Canadá, Bosnia, Catar, Suiza
// C: Brasil, Marruecos, Haití, Escocia
// D: Estados Unidos, Paraguay, Australia, Turquía
// E: Alemania, Curaçao, Costa de Marfil, Ecuador
// F: Países Bajos, Japón, Suecia, Túnez
// G: Bélgica, Egipto, Irán, Nueva Zelanda
// H: España, Cabo Verde, Arabia Saudita, Uruguay
// I: Francia, Senegal, Irak, Noruega
// J: Argentina, Argelia, Austria, Jordania
// K: Portugal, RD Congo, Uzbekistán, Colombia
// L: Inglaterra, Croacia, Ghana, Panamá

export const WC_MATCHES = [
  // ════ JUE 11-JUN — GRUPO A (INAUGURAL) ════
  {
    id: 'wc2026_a1_mex_saf_11jun',
    home: 'México', away: 'Sudáfrica',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.45,
    _hO: 1.45, _dO: 4.50, _aO: 7.50, _bestOdds: 1.45,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-11T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 11, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 65, probD: 22, probA: 13,
    insight: 'Partido INAUGURAL del Mundial 2026 en el Estadio Azteca. México (#15 FIFA) anfitrión vs Sudáfrica (#61), debutante tras 16 años de ausencia. Aguirre con Edson Álvarez, Hirving Lozano y Henry Martín. Sudáfrica depende de Mokoena y Foster. Factor altitud (2240m) + público local + estadística: el anfitrión gana 5 de los últimos 7 partidos inaugurales del Mundial. Pick MÁXIMA confianza.',
  },

  // ════ VIE 12-JUN — GRUPO B + GRUPO D (debut anfitriones Canadá y USA) ════
  {
    id: 'wc2026_b1_can_bih_12jun',
    home: 'Canadá', away: 'Bosnia',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 2.20, _dO: 3.10, _aO: 3.30, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-12T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 12, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 42, probD: 31, probA: 27,
    insight: 'Canadá co-anfitrión hace debut en casa (BMO Field Toronto). Sin Alphonso Davies (lesión larga) pero con Jonathan David, Buchanan y Larin. Bosnia clasificó tras 12 años eliminando a Italia en repechaje — equipo en racha y con Edin Džeko aún influyente. Doble 1X cubre victoria local o empate = escenario más probable.',
  },
  {
    id: 'wc2026_d1_usa_par_12jun',
    home: 'Estados Unidos', away: 'Paraguay',
    rec: 'Más de 2.5 goles',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.85,
    _bestOdds: 1.85,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-12T23:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 12, 20, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    insight: 'USA co-anfitrión debuta en casa (SoFi Stadium LA). Trío Pulisic-Reyna-Balogun garantiza ataque. Paraguay regresa al Mundial tras 16 años con Almirón, Antony Silva y Sosa — equipo ofensivo. Defensas medias en ambos lados. Over 2.5 con valor positivo: 7 de últimos 10 partidos de Paraguay tuvieron 3+ goles.',
  },

  // ════ SÁB 13-JUN — GRUPO C ════
  {
    id: 'wc2026_c1_bra_mar_13jun',
    home: 'Brasil', away: 'Marruecos',
    rec: 'Gana Brasil (Empate no válido)',
    conf: 'med', bvr: 4, bvrText: 'Media-Alta',
    stake: 50, odds: 1.80,
    _bestOdds: 1.80,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-13T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 13, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    insight: 'CHOQUE TITÁNICO. Brasil con Ancelotti, Vinicius, Rodrygo, Endrick — renovación generacional. Marruecos viene de 4to puesto en Qatar 2022 (Hakimi, Mazraoui, Saiss, Bono). Cuotas parejas en debut. ESA cubre el empate (escenario muy probable en debuts) y solo paga si Brasil gana. Modelo da 42% Brasil, 30% empate, 28% Marruecos.',
  },

  // ════ DOM 14-JUN — GRUPO E + GRUPO F ════
  {
    id: 'wc2026_e1_ger_cur_14jun',
    home: 'Alemania', away: 'Curaçao',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.18,
    _hO: 1.18, _dO: 7.50, _aO: 15.0, _bestOdds: 1.18,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-14T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 14, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 86, probD: 9, probA: 5,
    insight: 'Alemania de Nagelsmann recuperó identidad ofensiva con Musiala, Wirtz, Havertz, Kimmich. Vs Curaçao (#82 FIFA), debutante absoluto del Caribe, jugando ¡su primer partido Mundial de la historia! Diferencia abismal en plantel y experiencia. Cuota baja pero lock matemático.',
  },
  {
    id: 'wc2026_f1_ned_jpn_14jun',
    home: 'Países Bajos', away: 'Japón',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.40,
    _hO: 1.85, _dO: 3.50, _aO: 4.20, _bestOdds: 1.40,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-14T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 14, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 50, probD: 28, probA: 22,
    insight: 'Países Bajos con Van Dijk, Frimpong, Gakpo, Xavi Simons — generación renovada post Van Gaal. Japón #18 FIFA con plantel europeo elite (Endo, Mitoma, Kubo, Mt Itakura) — recordemos que ganó a Alemania y España en Qatar. Doble 1X cubre empate y victoria Oranje = escenario más probable según modelo.',
  },

  // ════ LUN 15-JUN — GRUPO G + GRUPO H ════
  {
    id: 'wc2026_g1_bel_egy_15jun',
    home: 'Bélgica', away: 'Egipto',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.55, _dO: 3.70, _aO: 5.80, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-15T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 15, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 56, probD: 25, probA: 19,
    insight: 'Bélgica con relevo generacional: De Bruyne capitán, Lukaku, Doku, Tielemans, Onana. Egipto regresa al Mundial tras ausencia 2022 con Salah, Trezeguet, Mohamed. Bélgica favorito claro pero Egipto siempre incómodo. Pick sólido sin sorpresas.',
  },
  {
    id: 'wc2026_h1_esp_cv_15jun',
    home: 'España', away: 'Cabo Verde',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.15,
    _hO: 1.15, _dO: 8.50, _aO: 18.0, _bestOdds: 1.15,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-15T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 15, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 88, probD: 8, probA: 4,
    insight: 'España campeona Euro 2024 con generación dorada: Lamine Yamal (18 años), Pedri (22), Rodri (Balón de Oro), Nico Williams. Ranking FIFA #1. Cabo Verde debutante absoluto #68 FIFA. Diferencia abismal. La única duda: cuántos goles. Lock matemático.',
  },

  // ════ MAR 16-JUN — GRUPO I + GRUPO J ════
  {
    id: 'wc2026_i1_fra_sen_16jun',
    home: 'Francia', away: 'Senegal',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.55, _dO: 4.10, _aO: 5.50, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-16T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 16, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 60, probD: 23, probA: 17,
    insight: 'Francia favorita matemática al título con Mbappé, Camavinga, Tchouameni — equipo más completo del torneo. Senegal trae Koulibaly, Mendy, Mané — campeón de África 2022. Senegal incómodo pero Francia un escalón arriba. Cuota 1.55 con valor positivo.',
  },
  {
    id: 'wc2026_j1_arg_alg_16jun',
    home: 'Argentina', away: 'Argelia',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.32,
    _hO: 1.32, _dO: 5.20, _aO: 8.50, _bestOdds: 1.32,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-16T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 16, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 76, probD: 16, probA: 8,
    insight: 'Argentina DEFENSORA DEL TÍTULO con núcleo 2022 intacto: Messi, Mac Allister, Julián Álvarez, Otamendi, Dibu Martínez. Argelia #41 FIFA con Mahrez como única estrella. Diferencia clara de nivel y experiencia. Scaloni rotará pero pondrá a Messi. Pick MÁXIMA confianza para la apertura del Grupo J.',
  },

  // ════ MIÉ 17-JUN — GRUPO K + GRUPO L ════
  {
    id: 'wc2026_k1_por_drc_17jun',
    home: 'Portugal', away: 'RD Congo',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.40,
    _hO: 1.40, _dO: 4.80, _aO: 7.50, _bestOdds: 1.40,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-17T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 17, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 68, probD: 20, probA: 12,
    insight: 'Portugal con Cristiano (41 años, última danza), Bernardo Silva, Bruno Fernandes, Rúben Dias, Vitinha. Roberto Martínez como técnico. RD Congo regresa al Mundial tras 50 años de ausencia — equipo histórico pero plantel mucho menor. Diferencia clara.',
  },
  {
    id: 'wc2026_l1_eng_cro_17jun',
    home: 'Inglaterra', away: 'Croacia',
    rec: 'Más de 2.5 goles',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.95,
    _bestOdds: 1.95,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-17T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 17, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    insight: 'CHOQUE DE TITANES. Inglaterra con Tuchel: Bellingham, Saka, Foden, Kane, Rice — talento ofensivo brutal. Croacia con Modrić retirado pero con Sucic, Kovacic, Petković. Repetición de la semifinal Rusia 2018. Ambos juegan ofensivo. 6 de últimos 10 partidos entre ambos tuvieron 3+ goles. Over 2.5 con valor.',
  },

  // ════ FASE DE GRUPOS — 2DOS PARTIDOS + 3RAS FECHAS ════
  {
    id: 'wc2026_e2_civ_ecu_14jun',
    home: 'Costa de Marfil', away: 'Ecuador',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.45,
    _hO: 1.74, _dO: 2.61, _aO: 2.17, _bestOdds: 1.45,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-14T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 14, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 42, probD: 31, probA: 27,
    insight: 'Costa de Marfil con Haller, Pepe, Kessié, Aurier — campeón Africa 2024 en casa. Ecuador con Caicedo, Estupiñán, Plata, Sarmiento. Pick conservador: Costa de Marfil gana o empata, cubre 73% del escenario.',
  },
  {
    id: 'wc2026_f2_swe_tun_14jun',
    home: 'Suecia', away: 'Túnez',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.35,
    _hO: 1.62, _dO: 2.43, _aO: 2.03, _bestOdds: 1.35,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-14T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 14, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 48, probD: 30, probA: 22,
    insight: 'Suecia con Isak, Gyökeres, Kulusevski — ofensiva top. Túnez sólido defensivamente pero con poco gol. Suecia es favorita pero el empate es escenario realista contra africanos disciplinados. Doble 1X cubre los dos.',
  },
  {
    id: 'wc2026_g2_irn_nzl_15jun',
    home: 'Irán', away: 'Nueva Zelanda',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.55, _dO: 2.79, _aO: 2.33, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-15T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 15, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 56, probD: 26, probA: 18,
    insight: 'Irán con Taremi, Azmoun, Jahanbakhsh — ranking FIFA 21, plantel completo en ligas europeas. Nueva Zelanda ranking 95, debut en Mundial tras 16 años. Diferencia clara de nivel.',
  },
  {
    id: 'wc2026_h2_sau_uru_15jun',
    home: 'Arabia Saudita', away: 'Uruguay',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.6,
    _hO: 1.92, _dO: 2.88, _aO: 1.60, _bestOdds: 1.6,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-15T13:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 15, 10, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 18, probD: 25, probA: 57,
    insight: 'Uruguay con Valverde, Bentancur, Núñez, Pellistri, Araújo. Bielsa al mando. Arabia Saudita ranking 60, depende del local Salem Al-Dawsari. Uruguay es claramente superior técnicamente.',
  },
  {
    id: 'wc2026_i2_irq_nor_16jun',
    home: 'Irak', away: 'Noruega',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.5,
    _hO: 1.80, _dO: 2.70, _aO: 1.50, _bestOdds: 1.5,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-16T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 16, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 12, probD: 22, probA: 66,
    insight: 'Noruega CON Haaland + Ødegaard + Solbakken. Ranking 13 FIFA. Irak ranking 58, vuelve al Mundial tras 40 años. Noruega favorita absoluta. Pick MÁXIMA.',
  },
  {
    id: 'wc2026_j2_aut_jor_16jun',
    home: 'Austria', away: 'Jordania',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.5,
    _hO: 1.50, _dO: 2.70, _aO: 2.25, _bestOdds: 1.5,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-16T13:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 16, 10, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 65, probD: 22, probA: 13,
    insight: 'Austria con Sabitzer, Alaba, Arnautović, Baumgartner — equipo top mundial 25. Jordania debut histórico, ranking 64. Austria favorita clara en partido clave del Grupo J (Argentina).',
  },
  {
    id: 'wc2026_k2_uzb_col_17jun',
    home: 'Uzbekistán', away: 'Colombia',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.86, _dO: 2.79, _aO: 1.55, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-17T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 17, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 14, probD: 24, probA: 62,
    insight: 'Colombia con James, Luis Díaz, Lerma, Mina, Cuadrado — generación finalista Copa América 2024. Uzbekistán debut, ranking 68. Diferencia técnica enorme.',
  },
  {
    id: 'wc2026_l2_gha_pan_17jun',
    home: 'Ghana', away: 'Panamá',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.85,
    _hO: 1.85, _dO: 3.33, _aO: 2.78, _bestOdds: 1.85,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-17T13:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 17, 10, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 51, probD: 25, probA: 24,
    insight: 'Ghana con Kudus, Partey, Salisu, Iñaki Williams — Black Stars reconstruidos. Panamá sólido CONCACAF pero con plantel menor. Ghana favorito en duelo parejo.',
  },
  {
    id: 'wc2026_a2_mex_kor_18jun',
    home: 'México', away: 'Corea del Sur',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.3,
    _hO: 1.56, _dO: 2.34, _aO: 1.95, _bestOdds: 1.3,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-18T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 18, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 47, probD: 30, probA: 23,
    insight: 'México local en Azteca con Vega, Edson Álvarez, Lozano, Jiménez. Corea del Sur con Son Heung-min, Lee Kang-in — rival serio. Doble 1X cubre el local + empate (77% del escenario).',
  },
  {
    id: 'wc2026_a3_rsa_cze_18jun',
    home: 'Sudáfrica', away: 'República Checa',
    rec: 'Doble X2', _recSide: 'x2',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.86, _dO: 2.79, _aO: 2.33, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-18T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 18, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 31, probD: 28, probA: 41,
    insight: 'Rep. Checa con Schick, Soucek, Souček, Hložek — europeos con plantel sólido. Sudáfrica sin grandes figuras tras el partido inaugural. Doble X2 cubre empate + visitante (69%).',
  },
  {
    id: 'wc2026_b2_can_qat_18jun',
    home: 'Canadá', away: 'Catar',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.4,
    _hO: 1.40, _dO: 2.52, _aO: 2.10, _bestOdds: 1.4,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-18T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 18, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 68, probD: 20, probA: 12,
    insight: 'Canadá local con Alphonso Davies, Jonathan David, Buchanan, Eustáquio. Catar ranking 53, peor que en 2022. Canadá favorito amplio en casa.',
  },
  {
    id: 'wc2026_b3_bih_sui_18jun',
    home: 'Bosnia', away: 'Suiza',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.85,
    _hO: 2.22, _dO: 3.33, _aO: 1.85, _bestOdds: 1.85,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-18T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 18, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 27, probD: 28, probA: 45,
    insight: 'Suiza ranking 19, Xhaka, Embolo, Akanji, Sommer — sólida. Bosnia con Pjanić ya retirado, Demirović y Dzeko al borde de retirada. Suiza superior.',
  },
  {
    id: 'wc2026_c2_bra_hai_18jun',
    home: 'Brasil', away: 'Haití',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.18,
    _hO: 1.18, _dO: 2.12, _aO: 1.77, _bestOdds: 1.18,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-18T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 18, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 86, probD: 9, probA: 5,
    insight: 'Brasil con Vinicius, Rodrygo, Endrick, Ancelotti — favorito mundial. Haití ranking 88, debut histórico. Diferencia abismal de nivel.',
  },
  {
    id: 'wc2026_c3_mar_sco_18jun',
    home: 'Marruecos', away: 'Escocia',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.65,
    _hO: 1.65, _dO: 2.97, _aO: 2.47, _bestOdds: 1.65,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-18T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 18, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 52, probD: 26, probA: 22,
    insight: 'Marruecos con Hakimi, Ziyech, Mazraoui, Bono — 4to puesto Qatar 2022. Escocia con McTominay, Robertson, Tierney — sólido pero menor jerarquía. Marruecos favorito.',
  },
  {
    id: 'wc2026_d2_usa_aus_18jun',
    home: 'Estados Unidos', away: 'Australia',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.65,
    _hO: 1.65, _dO: 2.97, _aO: 2.47, _bestOdds: 1.65,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-18T01:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 18, 22, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 52, probD: 26, probA: 22,
    insight: 'USA local con Pulisic, Reyna, Balogun, McKennie. Australia con Irvine, Mooy, Goodwin — Socceroos competitivos pero menos jerarquía. USA favorito en casa.',
  },
  {
    id: 'wc2026_d3_par_tur_18jun',
    home: 'Paraguay', away: 'Turquía',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.75,
    _hO: 2.10, _dO: 3.15, _aO: 1.75, _bestOdds: 1.75,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-18T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 18, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 25, probD: 28, probA: 47,
    insight: 'Turquía con Çalhanoğlu, Güler, Yıldız, Yıldız, Akaydin — joya europea. Paraguay sólido con Almirón y Sosa. Turquía superior técnicamente.',
  },
  {
    id: 'wc2026_e3_ger_civ_19jun',
    home: 'Alemania', away: 'Costa de Marfil',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.45,
    _hO: 1.45, _dO: 2.61, _aO: 2.17, _bestOdds: 1.45,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-19T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 19, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 56, probD: 24, probA: 20,
    insight: 'Alemania con Musiala, Wirtz, Havertz, Kimmich, Sané — reconstrucción Nagelsmann. Costa de Marfil campeón Africa con Haller, Pepe, Kessié. Pick favorito a Alemania.',
  },
  {
    id: 'wc2026_e4_cur_ecu_19jun',
    home: 'Curaçao', away: 'Ecuador',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.4,
    _hO: 1.68, _dO: 2.52, _aO: 1.40, _bestOdds: 1.4,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-19T13:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 19, 10, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 12, probD: 23, probA: 65,
    insight: 'Ecuador con Caicedo (Chelsea), Estupiñán (Brighton), Plata, Sarmiento — plantel Premier League. Curaçao debut absoluto, jugadores de ligas menores. Ecuador favorito amplio.',
  },
  {
    id: 'wc2026_f3_ned_swe_19jun',
    home: 'Países Bajos', away: 'Suecia',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.25,
    _hO: 1.50, _dO: 2.25, _aO: 1.88, _bestOdds: 1.25,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-19T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 19, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 57, probD: 26, probA: 17,
    insight: 'Países Bajos con Van Dijk, Frenkie de Jong, Gakpo, Xavi Simons, Dumfries. Suecia ofensiva con Isak y Gyökeres. Doble 1X cubre los 2 escenarios buenos (83% del escenario).',
  },
  {
    id: 'wc2026_f4_jpn_tun_19jun',
    home: 'Japón', away: 'Túnez',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.5,
    _hO: 1.50, _dO: 2.70, _aO: 2.25, _bestOdds: 1.5,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-19T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 19, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 58, probD: 26, probA: 16,
    insight: 'Japón con Mitoma, Kubo, Endo, Kamada, Tomiyasu — generación europea fuerte. Túnez sólido defensivamente pero con poca puntería. Japón favorito.',
  },
  {
    id: 'wc2026_g3_bel_irn_19jun',
    home: 'Bélgica', away: 'Irán',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.4,
    _hO: 1.40, _dO: 2.52, _aO: 2.10, _bestOdds: 1.4,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-19T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 19, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 62, probD: 24, probA: 14,
    insight: 'Bélgica con De Bruyne, Lukaku, Doku, Tielemans, Saelemaekers, Trossard. Irán con Taremi, Azmoun. Bélgica superior individualmente.',
  },
  {
    id: 'wc2026_g4_egy_nzl_19jun',
    home: 'Egipto', away: 'Nueva Zelanda',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.65,
    _hO: 1.65, _dO: 2.97, _aO: 2.47, _bestOdds: 1.65,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-19T13:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 19, 10, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 54, probD: 26, probA: 20,
    insight: 'Egipto con Mohamed Salah, Hegazi, Trezeguet, Mohamed — clásico africano. Nueva Zelanda debut tras 16 años. Egipto favorito por jerarquía.',
  },
  {
    id: 'wc2026_h3_esp_sau_19jun',
    home: 'España', away: 'Arabia Saudita',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.2,
    _hO: 1.20, _dO: 2.16, _aO: 1.80, _bestOdds: 1.2,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-19T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 19, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 82, probD: 12, probA: 6,
    insight: 'España campeona Eurocopa 2024 con Yamal, Pedri, Rodri, Morata, Olmo, Cucurella. Arabia ranking 60. España favorita absoluta. MÁXIMA confianza.',
  },
  {
    id: 'wc2026_h4_cpv_uru_19jun',
    home: 'Cabo Verde', away: 'Uruguay',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.4,
    _hO: 1.68, _dO: 2.52, _aO: 1.40, _bestOdds: 1.4,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-19T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 19, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 18, probD: 24, probA: 58,
    insight: 'Uruguay con Valverde, Bentancur, Núñez, Pellistri, Araújo — Bielsa al mando. Cabo Verde debut histórico Mundial. Uruguay favorito claro.',
  },
  {
    id: 'wc2026_i3_fra_irq_20jun',
    home: 'Francia', away: 'Irak',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.15,
    _hO: 1.15, _dO: 2.07, _aO: 1.72, _bestOdds: 1.15,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-20T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 20, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 87, probD: 9, probA: 4,
    insight: 'Francia con Mbappé, Dembélé, Saliba, Kanté, Tchouaméni, Coman, Camavinga. Subcampeón Mundial 2022. Irak ranking 58, debut tras décadas. Pick MÁXIMA.',
  },
  {
    id: 'wc2026_i4_sen_nor_20jun',
    home: 'Senegal', away: 'Noruega',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.86, _dO: 2.79, _aO: 2.33, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-20T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 20, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 42, probD: 30, probA: 28,
    insight: 'Senegal con Mané, Koulibaly, Sarr, Mendy — campeones Africa 2022. Noruega con Haaland y Ødegaard. Doble 1X cubre Senegal o empate (72%).',
  },
  {
    id: 'wc2026_j3_arg_aut_20jun',
    home: 'Argentina', away: 'Austria',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.55, _dO: 2.79, _aO: 2.33, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-20T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 20, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 60, probD: 24, probA: 16,
    insight: 'Argentina DEFENSORA del título con Messi, Mac Allister, Julián Álvarez, Otamendi, Dibu, Romero. Austria con Sabitzer, Alaba, Arnautović — rival serio europeo. Argentina favorita por jerarquía.',
  },
  {
    id: 'wc2026_j4_alg_jor_20jun',
    home: 'Argelia', away: 'Jordania',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.65,
    _hO: 1.65, _dO: 2.97, _aO: 2.47, _bestOdds: 1.65,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-20T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 20, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 50, probD: 28, probA: 22,
    insight: 'Argelia con Mahrez, Slimani, Bennacer, Mandi. Jordania debut histórico. Argelia con experiencia y jerarquía.',
  },
  {
    id: 'wc2026_k3_por_uzb_20jun',
    home: 'Portugal', away: 'Uzbekistán',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.18,
    _hO: 1.18, _dO: 2.12, _aO: 1.77, _bestOdds: 1.18,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-20T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 20, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 84, probD: 11, probA: 5,
    insight: 'Portugal con Cristiano, Bernardo Silva, Bruno Fernandes, Rúben Dias, Vitinha. Uzbekistán debut absoluto. Portugal favorito MÁXIMA.',
  },
  {
    id: 'wc2026_k4_cod_col_20jun',
    home: 'RD Congo', away: 'Colombia',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.65,
    _hO: 1.98, _dO: 2.97, _aO: 1.65, _bestOdds: 1.65,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-20T13:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 20, 10, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 25, probD: 25, probA: 50,
    insight: 'Colombia con James, Luis Díaz, Lerma, Mina, Cuadrado — semifinalista Copa América 2024. RD Congo con plantel africano menos cotizado. Colombia superior.',
  },
  {
    id: 'wc2026_l3_eng_gha_20jun',
    home: 'Inglaterra', away: 'Ghana',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.3,
    _hO: 1.30, _dO: 2.34, _aO: 1.95, _bestOdds: 1.3,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-20T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 20, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 73, probD: 18, probA: 9,
    insight: 'Inglaterra con Bellingham, Saka, Foden, Kane, Rice, Stones, Pickford — Tuchel maximiza potencial. Ghana con Kudus, Partey, Iñaki Williams. Inglaterra favorito MÁXIMA.',
  },
  {
    id: 'wc2026_l4_cro_pan_20jun',
    home: 'Croacia', away: 'Panamá',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.25,
    _hO: 1.25, _dO: 2.25, _aO: 1.88, _bestOdds: 1.25,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'pending',
    league: '🏆 Mundial 2026',
    date: '2026-06-20T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 20, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 76, probD: 17, probA: 7,
    insight: 'Croacia con Sucic, Kovacic, Petković — núcleo experimentado. Panamá sólido CONCACAF pero menor jerarquía. Croacia favorita amplia.',
  },
];
