// ─────────────────────────────────────────────────────────────────────────────
// 🏆 wc-matches.js — Picks IA por PARTIDO del Mundial 2026
//
// Calendario oficial Mundial 2026 (sorteo FIFA 5-dic-2025, Washington DC).
// Picks regulares (no outright) para los primeros 7 días del Mundial.
//
// ⚠️  REGLA (22-jun-2026 — Mauro): NO agregar picks con cuota ≤ 1.20.
//     Las cuotas ≤ 1.20 no rinden — el publisher (worker/index.js → runWcMatchesPublisher)
//     las filtra automáticamente y loguea SKIP. Los ya publicados quedan intactos.
//     Cuota mínima: 1.21.
// ─────────────────────────────────────────────────────────────────────────────

export const WC_MATCHES_PUBLISH_TS = Date.UTC(2026, 5, 9, 0, 0, 0); // publicación inmediata

function ART_ts(year, monthIdx, day, hourART, minART = 0) {
  return Date.UTC(year, monthIdx, day, hourART + 3, minART, 0);
}

// GRUPOS OFICIALES:
// A: México, Sudáfrica, Corea del Sur, República Checa
// B: Canadá, Bosnia, Catar, Suiza
// C: Brasil, Marruecos, Haití, Escocia
// D: Estados Unidos, Paraguay, Australia, Turquía
// E: Alemania, Curaçao, Costa de Marfil, Ecuador
// F: Países Bajos, Japón, Suecia, Túnez
// G: Bélgica, Egipto, Irán, Nueva Zelanda
// H: España, Cabo Verde, Arabia Saudita, Uruguay
// I: Francia, Senegal, Irak, Noruega
// J: Argentina, Argelia, Austria, Jordania
// K: Portugal, RD Congo, Uzbekistán, Colombia
// L: Inglaterra, Croacia, Ghana, Panamá

export const WC_MATCHES = [
  // ════ JUE 11-JUN — GRUPO A (INAUGURAL) ════
  {
    id: 'wc2026_a1_mex_saf_11jun',
    home: 'México', away: 'Sudáfrica',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.45,
    _hO: 1.45, _dO: 4.50, _aO: 7.50, _bestOdds: 1.45,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '2-0',
    pl: 76.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-11T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 11, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 65, probD: 22, probA: 13,
    insight: 'Partido INAUGURAL del Mundial 2026 en el Estadio Azteca. México (#15 FIFA) anfitrión vs Sudáfrica (#61), debutante tras 16 años de ausencia. Aguirre con Edson Álvarez, Hirving Lozano y Henry Martín. Sudáfrica depende de Mokoena y Foster. Factor altitud (2240m) + público local + estadística: el anfitrión gana 5 de los últimos 7 partidos inaugurales del Mundial. Pick MÁXIMA confianza.',
  },

  // ════ VIE 12-JUN — GRUPO B + GRUPO D (debut anfitriones Canadá y USA) ════
  {
    id: 'wc2026_b1_can_bih_12jun',
    home: 'Canadá', away: 'Bosnia',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 2.20, _dO: 3.10, _aO: 3.30, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '1-1',
    pl: 71.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-12T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 12, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 42, probD: 31, probA: 27,
    insight: 'Canadá co-anfitrión hace debut en casa (BMO Field Toronto). Sin Alphonso Davies (lesión larga) pero con Jonathan David, Buchanan y Larin. Bosnia clasificó tras 12 años eliminando a Italia en repechaje — equipo en racha y con Edin Džeko aún influyente. Doble 1X cubre victoria local o empate = escenario más probable.',
  },
  {
    id: 'wc2026_d1_usa_par_12jun',
    home: 'Estados Unidos', away: 'Paraguay',
    rec: 'Más de 2.5 goles',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.85,
    _bestOdds: 1.85,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '4-1',
    pl: 110.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-12T23:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 12, 20, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    insight: 'USA co-anfitrión debuta en casa (SoFi Stadium LA). Trío Pulisic-Reyna-Balogun garantiza ataque. Paraguay regresa al Mundial tras 16 años con Almirón, Antony Silva y Sosa — equipo ofensivo. Defensas medias en ambos lados. Over 2.5 con valor positivo: 7 de últimos 10 partidos de Paraguay tuvieron 3+ goles.',
  },

  // ════ SÁB 13-JUN — GRUPO C ════
  {
    id: 'wc2026_c1_bra_mar_13jun',
    home: 'Brasil', away: 'Marruecos',
    rec: 'Gana Brasil (Empate no válido)',
    conf: 'med', bvr: 4, bvrText: 'Media-Alta',
    stake: 50, odds: 1.80,
    _bestOdds: 1.80,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'void',
    finalScore: '1-1',
    pl: 0,
    league: '🏆 Mundial 2026',
    date: '2026-06-13T19:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 13, 16, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    insight: 'CHOQUE TITÁNICO. Brasil con Ancelotti, Vinicius, Rodrygo, Endrick — renovación generacional. Marruecos viene de 4to puesto en Qatar 2022 (Hakimi, Mazraoui, Saiss, Bono). Cuotas parejas en debut. ESA cubre el empate (escenario muy probable en debuts) y solo paga si Brasil gana. Modelo da 42% Brasil, 30% empate, 28% Marruecos.',
  },

  // ════ DOM 14-JUN — GRUPO E + GRUPO F ════
  {
    id: 'wc2026_e1_ger_cur_14jun',
    home: 'Alemania', away: 'Curaçao',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.18,
    _hO: 1.18, _dO: 7.50, _aO: 15.0, _bestOdds: 1.18,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '7-1',
    pl: 30.6,
    league: '🏆 Mundial 2026',
    date: '2026-06-14T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 14, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 86, probD: 9, probA: 5,
    insight: 'Alemania de Nagelsmann recuperó identidad ofensiva con Musiala, Wirtz, Havertz, Kimmich. Vs Curaçao (#82 FIFA), debutante absoluto del Caribe, jugando ¡su primer partido Mundial de la historia! Diferencia abismal en plantel y experiencia. Cuota baja pero lock matemático.',
  },
  {
    id: 'wc2026_f1_ned_jpn_14jun',
    home: 'Países Bajos', away: 'Japón',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.40,
    _hO: 1.85, _dO: 3.50, _aO: 4.20, _bestOdds: 1.40,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '2-2',
    pl: 52.0,
    league: '🏆 Mundial 2026',
    date: '2026-06-14T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 14, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 50, probD: 28, probA: 22,
    insight: 'Países Bajos con Van Dijk, Frimpong, Gakpo, Xavi Simons — generación renovada post Van Gaal. Japón #18 FIFA con plantel europeo elite (Endo, Mitoma, Kubo, Mt Itakura) — recordemos que ganó a Alemania y España en Qatar. Doble 1X cubre empate y victoria Oranje = escenario más probable según modelo.',
  },

  // ════ LUN 15-JUN — GRUPO G + GRUPO H ════
  {
    id: 'wc2026_g1_bel_egy_15jun',
    home: 'Bélgica', away: 'Egipto',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.55, _dO: 3.70, _aO: 5.80, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'loss',
    finalScore: '1-1',
    pl: -130.0,
    league: '🏆 Mundial 2026',
    date: '2026-06-15T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 15, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 56, probD: 25, probA: 19,
    insight: 'Bélgica con relevo generacional: De Bruyne capitán, Lukaku, Doku, Tielemans, Onana. Egipto regresa al Mundial tras ausencia 2022 con Salah, Trezeguet, Mohamed. Bélgica favorito claro pero Egipto siempre incómodo. Pick sólido sin sorpresas.',
  },
  {
    id: 'wc2026_h1_esp_cv_15jun',
    home: 'España', away: 'Cabo Verde',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.15,
    _hO: 1.15, _dO: 8.50, _aO: 18.0, _bestOdds: 1.15,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'loss',
    finalScore: '0-0',
    pl: -170.0,
    league: '🏆 Mundial 2026',
    date: '2026-06-15T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 15, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 88, probD: 8, probA: 4,
    insight: 'España campeona Euro 2024 con generación dorada: Lamine Yamal (18 años), Pedri (22), Rodri (Balón de Oro), Nico Williams. Ranking FIFA #1. Cabo Verde debutante absoluto #68 FIFA. Diferencia abismal. La única duda: cuántos goles. Lock matemático.',
  },

  // ════ MAR 16-JUN — GRUPO I + GRUPO J ════
  {
    id: 'wc2026_i1_fra_sen_16jun',
    home: 'Francia', away: 'Senegal',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.55, _dO: 4.10, _aO: 5.50, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '3-1',
    pl: 71.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-16T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 16, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 60, probD: 23, probA: 17,
    insight: 'Francia favorita matemática al título con Mbappé, Camavinga, Tchouameni — equipo más completo del torneo. Senegal trae Koulibaly, Mendy, Mané — campeón de África 2022. Senegal incómodo pero Francia un escalón arriba. Cuota 1.55 con valor positivo.',
  },
  {
    id: 'wc2026_j1_arg_alg_16jun',
    home: 'Argentina', away: 'Argelia',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.32,
    _hO: 1.32, _dO: 5.20, _aO: 8.50, _bestOdds: 1.32,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '3-0',
    pl: 54.4,
    league: '🏆 Mundial 2026',
    date: '2026-06-16T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 16, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 76, probD: 16, probA: 8,
    insight: 'Argentina DEFENSORA DEL TÍTULO con núcleo 2022 intacto: Messi, Mac Allister, Julián Álvarez, Otamendi, Dibu Martínez. Argelia #41 FIFA con Mahrez como única estrella. Diferencia clara de nivel y experiencia. Scaloni rotará pero pondrá a Messi. Pick MÁXIMA confianza para la apertura del Grupo J.',
  },

  // ════ MIÉ 17-JUN — GRUPO K + GRUPO L ════
  {
    id: 'wc2026_k1_por_drc_17jun',
    home: 'Portugal', away: 'RD Congo',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.40,
    _hO: 1.40, _dO: 4.80, _aO: 7.50, _bestOdds: 1.40,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'loss',
    finalScore: '1-1',
    pl: -130.0,
    league: '🏆 Mundial 2026',
    date: '2026-06-17T16:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 17, 13, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 68, probD: 20, probA: 12,
    insight: 'Portugal con Cristiano (41 años, última danza), Bernardo Silva, Bruno Fernandes, Rúben Dias, Vitinha. Roberto Martínez como técnico. RD Congo regresa al Mundial tras 50 años de ausencia — equipo histórico pero plantel mucho menor. Diferencia clara.',
  },
  {
    id: 'wc2026_l1_eng_cro_17jun',
    home: 'Inglaterra', away: 'Croacia',
    rec: 'Más de 2.5 goles',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.95,
    _bestOdds: 1.95,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '4-2',
    pl: 123.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-17T22:00:00.000Z',
    commenceTs: ART_ts(2026, 5, 17, 19, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    insight: 'CHOQUE DE TITANES. Inglaterra con Tuchel: Bellingham, Saka, Foden, Kane, Rice — talento ofensivo brutal. Croacia con Modrić retirado pero con Sucic, Kovacic, Petković. Repetición de la semifinal Rusia 2018. Ambos juegan ofensivo. 6 de últimos 10 partidos entre ambos tuvieron 3+ goles. Over 2.5 con valor.',
  },

  // ════ DOM 21-JUN — 2da fecha Grupos F + G + H ════
  {
    id: 'wc2026_f3_tun_jpn_21jun',
    home: 'Túnez', away: 'Japón',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.65,
    _hO: 4.50, _dO: 3.20, _aO: 1.65, _bestOdds: 1.65,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '0-4',
    pl: 84.50,
    league: '🏆 Mundial 2026',
    date: '2026-06-21T04:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 21, 4, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 22, probD: 26, probA: 52,
    insight: 'Japón con Mitoma, Kubo, Endo, Kamada, Tomiyasu — generación europea fuerte. Túnez sólido defensivamente pero con poca pegada. Japón es claramente superior técnicamente y necesita 3 puntos.',
  },
  {
    id: 'wc2026_h3_esp_sau_21jun',
    home: 'España', away: 'Arabia Saudita',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.20,
    _hO: 1.20, _dO: 7.00, _aO: 14.00, _bestOdds: 1.20,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '4-0',
    pl: 34.00,
    league: '🏆 Mundial 2026',
    date: '2026-06-21T16:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 21, 16, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 82, probD: 12, probA: 6,
    insight: 'España campeona Eurocopa 2024 con Yamal, Pedri, Rodri, Morata, Olmo, Cucurella. Arabia Saudita ranking 60. España favorita absoluta. MÁXIMA confianza.',
  },
  {
    id: 'wc2026_g3_bel_irn_21jun',
    home: 'Bélgica', away: 'Irán',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.40,
    _hO: 1.40, _dO: 4.80, _aO: 7.50, _bestOdds: 1.40,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'loss',
    finalScore: '0-0',
    pl: -130.00,
    league: '🏆 Mundial 2026',
    date: '2026-06-21T19:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 21, 19, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 62, probD: 24, probA: 14,
    insight: 'Bélgica con De Bruyne, Lukaku, Doku, Tielemans, Saelemaekers, Trossard. Irán con Taremi, Azmoun. Bélgica superior individualmente.',
  },
  {
    id: 'wc2026_h4_uru_cpv_21jun',
    home: 'Uruguay', away: 'Cabo Verde',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.40,
    _hO: 1.40, _dO: 4.50, _aO: 8.00, _bestOdds: 1.40,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'loss',
    finalScore: '2-2',
    pl: -130.00,
    league: '🏆 Mundial 2026',
    date: '2026-06-21T22:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 21, 22, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 58, probD: 24, probA: 18,
    insight: 'Uruguay con Valverde, Bentancur, Núñez, Pellistri, Araújo — Bielsa al mando. Cabo Verde debut histórico Mundial sin grandes figuras. Uruguay favorito claro.',
  },
  {
    id: 'wc2026_g4_nzl_egy_21jun',
    home: 'Nueva Zelanda', away: 'Egipto',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.65,
    _hO: 4.50, _dO: 3.20, _aO: 1.65, _bestOdds: 1.65,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '1-3',
    pl: 84.50,
    league: '🏆 Mundial 2026',
    date: '2026-06-22T01:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 22, 1, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 22, probD: 24, probA: 54,
    insight: 'Egipto con Mohamed Salah, Hegazi, Trezeguet, Mohamed — figuras y experiencia. Nueva Zelanda debut tras 16 años, plantel ligas menores. Egipto favorito por jerarquía.',
  },

  // ════ LUN 22-JUN — 3ra fecha Grupos I + J ════
  {
    id: 'wc2026_j3_arg_aut_22jun',
    home: 'Argentina', away: 'Austria',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.55, _dO: 3.80, _aO: 5.50, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '2-0',
    pl: 71.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-22T17:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 22, 17, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 60, probD: 24, probA: 16,
    insight: 'Argentina DEFENSORA del título con Messi, Mac Allister, Julián Álvarez, Otamendi, Dibu Martínez, Romero. Austria con Sabitzer, Alaba, Arnautović — rival serio europeo. Argentina favorita por jerarquía en Dallas Stadium.',
  },
  {
    id: 'wc2026_i3_fra_irq_22jun',
    home: 'Francia', away: 'Irak',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 6, bvrText: 'Máxima',
    stake: 170, odds: 1.15,
    _hO: 1.15, _dO: 8.00, _aO: 18.00, _bestOdds: 1.15,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '3-0',
    pl: 25.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-22T21:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 22, 21, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 87, probD: 9, probA: 4,
    insight: 'Francia con Mbappé, Dembélé, Saliba, Kanté, Tchouaméni, Coman, Camavinga. Subcampeón Mundial 2022. Irak ranking 58, debut tras décadas. Pick MÁXIMA.',
  },
  {
    id: 'wc2026_i4_nor_sen_22jun',
    home: 'Noruega', away: 'Senegal',
    rec: 'Doble 1X', _recSide: '1x',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.55,
    _hO: 1.95, _dO: 3.50, _aO: 3.80, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '3-2',
    pl: 71.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-23T00:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 23, 0, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 42, probD: 30, probA: 28,
    insight: 'Noruega con Haaland + Ødegaard + Solbakken. Ranking 13 FIFA. Senegal con Mané, Koulibaly, Sarr, Mendy — campeones Africa 2022. Pareja durísimo. Doble 1X cubre Noruega o empate (72% del escenario).',
  },
  // ════ MIÉ 24-JUN — 3ra fecha Grupos A + C ════
  {
    id: 'wc2026_a3_mex_cze_24jun',
    home: 'México', away: 'República Checa',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 110, odds: 1.85,
    _hO: 1.85, _dO: 3.40, _aO: 4.50, _bestOdds: 1.85,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '3-0',
    pl: 93.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-25T01:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 25, 1, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 56, probD: 26, probA: 18,
    insight: 'México local en Azteca, ya clasificado tras vencer Sudáfrica 2-0. Tiene plantel sólido (Lozano, Vega, Álvarez, Ochoa). República Checa eliminada o al límite, juega sin presión pero sin plantilla top. Pick value en cuota 1.85.',
  },
  {
    id: 'wc2026_c3_mar_hti_24jun',
    home: 'Marruecos', away: 'Haití',
    rec: 'Más de 2.5 goles', _recSide: 'over',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 110, odds: 1.75,
    _hO: 1.30, _dO: 5.50, _aO: 12.00, _bestOdds: 1.75,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '4-2',
    pl: 82.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-24T22:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 24, 22, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 72, probD: 18, probA: 10,
    insight: 'Marruecos (semifinalista Qatar 2022) con Hakimi, En-Nesyri, Ziyech, Mazraoui. Necesita ganar bien para asegurar clasificación. Haití defensa débil. Goles esperables (xG combinado >2.8).',
  },
  // ════ JUE 25-JUN — 3ra fecha Grupos D + E + F ════
  {
    id: 'wc2026_e3_ger_eqg_25jun',
    home: 'Alemania', away: 'Ecuador',
    rec: 'Más de 2.5 goles', _recSide: 'over',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.66,
    _hO: 1.583, _dO: 5.03, _aO: 5.39, _bestOdds: 1.66,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win', finalScore: '1-2', pl: 85.80,
    league: '🏆 Mundial 2026',
    date: '2026-06-25T23:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 25, 23, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 58, probD: 24, probA: 18,
    insight: 'Alemania con Musiala, Wirtz, Havertz, Kimmich — generación ofensiva fuerte. Ecuador defensa media. Ambos equipos pelean por avanzar. Promedio goles partidos Alemania en grupos: 3.2. Over 2.5 con valor.',
  },
  {
    id: 'wc2026_f3_ned_tun_25jun',
    home: 'Países Bajos', away: 'Túnez',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 110, odds: 1.08,
    _hO: 1.08, _dO: 9.0, _aO: 22.0, _bestOdds: 1.08,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win', finalScore: '3-1', pl: 8.80,
    league: '🏆 Mundial 2026',
    date: '2026-06-26T02:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 26, 2, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 60, probD: 23, probA: 17,
    insight: 'Países Bajos con Van Dijk, Gakpo, Frimpong, Xavi Simons — plantel top europeo. Túnez ya eliminado tras 0-4 vs Japón, juega sin objetivo. NL necesita ganar para asegurar 1er puesto del grupo.',
  },
  // ════ VIE 26-JUN — 3ra fecha Grupos G + H ════
  {
    id: 'wc2026_g5_egy_irn_26jun',
    home: 'Egipto', away: 'Irán',
    rec: 'Empate', _recSide: 'draw',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 80, odds: 2.74,
    _hO: 2.55, _dO: 2.74, _aO: 3.87, _bestOdds: 2.74,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win', finalScore: '1-1', pl: 139.20,
    league: '🏆 Mundial 2026',
    date: '2026-06-27T02:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 27, 2, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 36, probD: 32, probA: 32,
    insight: 'Egipto y Irán parejos en el grupo. Egipto viene de tumbar a Nueva Zelanda 3-1 (Salah brilla). Irán empató 0-0 con Bélgica. Ambos pueden clasificar con empate. Probabilidad empate alta (32%) — cuota 3.20 ofrece valor matemático.',
  },
  {
    id: 'wc2026_h5_uru_esp_26jun',
    home: 'Uruguay', away: 'España',
    rec: 'Más de 2.5 goles', _recSide: 'over',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 110, odds: 1.87,
    _hO: 2.50, _dO: 3.30, _aO: 2.80, _bestOdds: 1.87,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'loss', finalScore: '0-1', pl: -110.00,
    league: '🏆 Mundial 2026',
    date: '2026-06-26T23:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 26, 23, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 26, probD: 28, probA: 46,
    insight: 'España (4-0 vs Arabia Saudita, top ataque con Yamal, Oyarzabal) vs Uruguay (2-2 con Cabo Verde — defensa floja). Ambos juegan ofensivos. España necesita ganar para 1er lugar. Goles esperables. Promedio combinado xG: 2.9.',
  },
  // ════ MAR 23-JUN — 2da fecha Grupos K + L ════
  {
    id: 'wc2026_k2_por_uzb_23jun',
    home: 'Portugal', away: 'Uzbekistán',
    rec: 'Más de 2.5 goles', _recSide: 'over',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 110, odds: 1.75,
    _hO: 1.30, _dO: 5.20, _aO: 10.00, _bestOdds: 1.75,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '5-0',
    pl: 82.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-23T17:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 23, 17, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 70, probD: 20, probA: 10,
    insight: 'Portugal con Cristiano, Bernardo Silva, Bruno Fernandes, Vitinha, Bernardo Silva — top mundial. Uzbekistán debutante con plantel modesto. Portugal viene de empatar 1-1 con RD Congo (no pudo dominar). Necesita ganar y bien. Goles esperables.',
  },
  {
    id: 'wc2026_l2_eng_gha_23jun',
    home: 'Inglaterra', away: 'Ghana',
    rec: 'Más de 2.5 goles', _recSide: 'over',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 130, odds: 1.80,
    _hO: 1.45, _dO: 4.50, _aO: 7.00, _bestOdds: 1.80,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'loss',
    finalScore: '0-0',
    pl: -130.0,
    league: '🏆 Mundial 2026',
    date: '2026-06-23T20:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 23, 20, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 60, probD: 24, probA: 16,
    insight: 'Inglaterra (Bellingham, Kane, Saka, Foden, Rice) — venía de 4-2 vs Croacia (Over 2.5 cumplido). Ghana con Kudus, Iñaki Williams, Salisu, abre el partido buscando contragolpes. Los partidos de Inglaterra siempre son de muchos goles. Over 2.5 con valor.',
  },
  {
    id: 'wc2026_l3_pan_cro_23jun',
    home: 'Panamá', away: 'Croacia',
    rec: 'Gana Visitante', _recSide: 'away',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 80, odds: 1.55,
    _hO: 5.50, _dO: 3.60, _aO: 1.55, _bestOdds: 1.55,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '0-1',
    pl: 44.0,
    league: '🏆 Mundial 2026',
    date: '2026-06-23T23:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 23, 23, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 16, probD: 24, probA: 60,
    insight: 'Croacia con Modrić (40 años pero leyenda), Sucic, Kovacic, Kramaric, Petković — finalistas Mundial 2018, semi 2022. Necesita ganar tras 2-4 vs Inglaterra. Panamá modesto, plantel pobre. Croacia clarísimo favorito.',
  },
  {
    id: 'wc2026_k3_col_cod_23jun',
    home: 'Colombia', away: 'RD Congo',
    rec: 'Gana Local', _recSide: 'home',
    conf: 'high', bvr: 5, bvrText: 'Alta',
    stake: 110, odds: 1.75,
    _hO: 1.75, _dO: 3.40, _aO: 4.50, _bestOdds: 1.75,
    _bookKey: 'dbbet', _bookLabel: 'DBbet',
    result: 'win',
    finalScore: '1-0',
    pl: 82.5,
    league: '🏆 Mundial 2026',
    date: '2026-06-24T02:00:00.000Z',
    commenceTs: Date.UTC(2026, 5, 24, 2, 0, 0),
    _sportKey: 'soccer_fifa_world_cup',
    _wcMatch: true,
    probH: 58, probD: 24, probA: 18,
    insight: 'Colombia con Luis Díaz, James Rodríguez, Cuadrado, Lerma, Borja — generación sólida. Local en Estadio Akron (Guadalajara MX, condiciones favorables). RD Congo viene de empatar 1-1 con Portugal pero tuvo defensa muy castigada. Colombia favorita.',
  },
];

