name = "gambeta-x-bot"
main = "index.js"
compatibility_date = "2026-05-01"

[vars]
BOT_MODE = "off"

[triggers]
crons = ["17 * * * *", "23 12 * * *", "30 12 * * *", "13 21 * * *"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "CACHE_KV"
id = "1d4b161e78db4de9a9b806f369c73ceb"
